name: Deploy Planora Backend

on:
  push:
    branches: [ main ] # Triggers only on push to main branch

jobs:
  deploy:
    name: Deploy to OCI
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/planora-server
            git pull origin main
            
            # Disable Telemetry and interactive prompts for faster first-run
            export CHECKPOINT_DISABLE=1
            export PRISMA_TELEMETRY_INFORMATION_COLLECTION_DISABLE=1
            
            bun install
            
            # Restart the server
            pm2 restart planora-backend || pm2 start "bun run start" --name "planora-backend"

